### ISSUE TITLE
nuget did not find the EasyCaching.FreeRedis?

### ISSUE THREAD

**Issue by xubinhua888** [easycaching-contrib/ec-freeredis#3]
nuget did not find the EasyCaching.FreeRedis?

**Comment by catcherwong** [comment]
https://www.nuget.org/packages/EasyCaching.FreeRedis

@Memoyu  We should release a stable version,

**Comment by Memoyu** [comment]
Yes, i will do it

**Comment by Memoyu** [comment]
@xubinhua888 
Done, you can try!
>PM> dotnet add package EasyCaching.FreeRedis

**Comment by xubinhua888** [comment]
Thanks. Do you have plans to implement EasyCaching.Bus.FreeRedis?

**Comment by Memoyu** [comment]
> Thanks. Do you have plans to implement EasyCaching.Bus.FreeRedis?

@xubinhua888 
Yes, we will finish it soon

**Comment by xubinhua888** [comment]
nuget did not find the EasyCaching.Bus.FreeRedis?
